services:
  - type: web
    name: tachlesai
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SSL_ENABLED
        value: true
      - key: PORT
        fromService:
          name: tachlesai
          type: web
          property: port
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      # If you have an existing database
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /api/health 